name: CI/CD Pipeline  # ✅ only once, at the very top

on:
  push:
    branches:
      - main  # ✅ runs on push to main branch

jobs:
  deploy:  # ✅ ONE job, named deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/My-Project  # ✅ Use your actual server project path
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            # restart your app here if needed
